#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define VER_MAJOR   0
#define VER_MINOR   1
#define VER_REV     0
#define VER_DEV     2
#define BUILD       65

#define IDD_DIALOG1                             100
#define IDD_DIALOG2                             101
#define IDD_DIALOG3                             102
#define ID_SAVE                                 40000
#define ID_ABOUT_OK                             40001
#define ID_EDIT                                 40002
#define ID_ABOUT_UPDATE                         40003
#define ID_RESET                                40004
#define ID_ABOUT                                40005
#define ID_ABOUT_VIEW_REPO                      40006
#define ID_CLOSE                                40007
#define ID_C2_INS                               40008
#define ID_C1_DEL                               40009
#define ID_C1_INS                               40010
#define ID_C3_INS                               40011
#define ID_C4_INS                               40012
#define ID_C5_INS                               40013
#define ID_C2_DEL                               40014
#define ID_C3_DEL                               40015
#define ID_C4_DEL                               40016
#define ID_C5_DEL                               40017
#define IDS_C2                                  40018
#define IDS_C1                                  40019
#define IDS_C3                                  40020
#define IDS_C4                                  40021
#define IDS_C5                                  40022
#define IDC_C2_EDIT                             40023
#define IDC_C1_EDIT                             40024
#define IDC_C3_EDIT                             40025
#define IDC_C4_EDIT                             40026
#define IDC_C5_EDIT                             40027
#define IDG_TALLY_COUNTER                       40028
#define IDS_ABOUT                               40029
#define ID_ABOUT_DEBUG                          40030
#define ID_EDITBOX_CANCEL                       40031
#define ID_OPEN                                 40032
#define IDC_EDITBOX_C1_EDIT                     40033
#define IDS_EDITBOX_C2                          40034
#define IDC_EDITBOX_C2_EDIT                     40035
#define IDS_EDITBOX_C3                          40036
#define IDS_EDITBOX_C1                          40037
#define IDC_EDITBOX_C3_EDIT                     40038
#define IDS_EDITBOX_C4                          40039
#define IDC_EDITBOX_C4_EDIT                     40040
#define IDS_EDITBOX_C5                          40041
#define IDC_EDITBOX_C5_EDIT                     40042
#define ID_EDITBOX_OK                           40043
